name: Push New Image

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.*/**'
      - 'README.md'

env:
  IMAGE_REPO: wesdobry 
  IMAGE_NAME: rsync-ssh-delay

jobs:
  Push-New-Image:
    runs-on: 	ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get environment variables
        uses: FranzDiebold/github-env-vars-action@v2

      - name: Set tag
        run: |
          if [ "$CI_ACTION_REF_NAME_SLUG" == 'main' ]
          then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=$CI_ACTION_REF_NAME_SLUG" >> $GITHUB_ENV
          fi

      - name: Print image tag
        run: |
          echo "Branch: $CI_ACTION_REF_NAME"
          echo "Image Tag: ${{ env.IMAGE_TAG }}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Update README on Docker Hub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASS }}
        with:
          provider: dockerhub
          destination_container_repo:  ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}
          readme_file: README.md
